service: python-projects

provider:
  name: aws
  runtime: python3.6
  versionFunctions: false
  memorySize: 128
  region: us-west-2

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get

plugins:
  - serverless-wsgi

custom:
  wsgi:
    app: handler.app
    packRequirements: false
    pythonBin: python3
